#ifndef  TIMER1_CONFIG_H
#define  TIMER1_CONFIG_H

/**
 * @brief 
 * 
 * TIMER1_PRESCALLER_1
 * TIMER1_PRESCALLER_8
 * TIMER1_PRESCALLER_64
 * TIMER1_PRESCALLER_256
 * TIMER1_PRESCALLER_1024
 */

#define TIMER1_PRESCALLER   TIMER1_PRESCALLER_1


#endif // TIMER1_INTERFACE_H